### ISSUE TITLE
ルートフォルダ以外への対応

### ISSUE THREAD

**Issue by nazonoSAUNA** [Mr-Ojii/MotionTracking_MKII_Plus#15]
全ファイルを入れた際にそこそこの数となるため、できればルートに置きたくないので。
![image](https://github.com/Mr-Ojii/MotionTracking_MKII_Plus/assets/99536641/01dc191c-8815-4b2e-af82-712bc980f02a)

**Comment by Mr-Ojii** [comment]
r84で `MotionTrackingMKIIPlus.auf`と同一ディレクトリ内に存在する`MotionTracking_model`ディレクトリをモデルの配置場所とすることで、ルートディレクトリではない箇所にモデルを置くことを可能としました。

r84以降ではモデルの配置場所を上記の場所に限定したため、ルートディレクトリに配置したとしても読み込まなくなりました。
よって、移動をお願いいたします。
